name: Docker Compose CI

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Docker et Docker Compose
        run: |
          docker --version
          docker compose version || true

      - name: Créer docker-compose.yml
        run: |
          cat > docker-compose.yml <<'EOF'
          version: '3.8'
          services:
            db:
              image: mysql:8.0
              restart: always
              environment:
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wpuser
                MYSQL_PASSWORD: wppass
                MYSQL_ROOT_PASSWORD: rootpass
              ports:
                - "3306:3306"

            wordpress:
              image: wordpress:latest
              restart: always
              depends_on:
                - db
              ports:
                - "8080:80"
              environment:
                WORDPRESS_DB_HOST: db:3306
                WORDPRESS_DB_USER: wpuser
                WORDPRESS_DB_PASSWORD: wppass
                WORDPRESS_DB_NAME: wordpress

            adminer:
              image: adminer
              restart: always
              ports:
                - "8081:8080"
          EOF

      - name: Lancer les services Docker
        run: |
          docker compose up -d
          docker compose ps

      - name: Tester la connexion MySQL
        run: |
          docker exec db mysql -uwpuser -pwppass -e "SHOW DATABASES;"
